.decl byNum(v0:number, v1:__SYS_TYPE__Animal) // int x Cat
.decl Animal_byStr(v0:symbol, v1:__SYS_TYPE__Animal) // string x Animal
.decl Cat_A(v0:__SYS_TYPE__Animal) // Cat
.decl Cat_B(v0:__SYS_TYPE__Animal) // Cat
.decl Animal(v0:__SYS_TYPE__Animal) // Animal
.decl Cat(v0:__SYS_TYPE__Animal) // Cat
.decl PersianCat(v0:__SYS_TYPE__Animal) // PersianCat
.type __SYS_TYPE_Animal_byStr = [v0:symbol]
.type __SYS_TYPE_byNum = [v0:number]
.type __SYS_TYPE__Animal = [v0:__SYS_TYPE_Animal_byStr, v1:__SYS_TYPE_byNum]
Animal_byStr("foo", [["foo"], nil]), PersianCat([["foo"], nil]) :- 1=1.
byNum(42, [nil, [42]]), PersianCat([nil, [42]]) :- 1=1.
Animal_byStr("A", [["A"], nil]), Cat([["A"], nil]), Cat_A([["A"], nil]) :- 1=1.
Animal_byStr("B", [["B"], nil]), Cat([["B"], nil]), Cat_B([["B"], nil]) :- 1=1.
Animal(v0) :- Cat(v0).
Cat(v0) :- PersianCat(v0).
