.decl __f_oo_bar(v0:symbol) // string
.decl f_oo_bar2(v0:number, v1:symbol) // int x string
.output f_oo_bar2
.decl p1(v0:number) // int
.decl p2(v0:number, v1:number) // int x int
.decl p3(v0:number, v1:number) // int x int
.decl p4(v0:number) // int
.decl p5(v0:number) // int
.decl p6(v0:number) // int
.output p6
.decl Foo123(v0:number, v1:number) // int x int
.decl Bar123(v0:symbol) // string
.decl FooBar(v0:number, v1:symbol, v2:number) // int x string x int
.decl p(v0:number) // int
.decl Bar(v0:number) // int
.decl Foo(v0:number) // int
.decl BarFoo(v0:number, v1:symbol) // int x string
.decl A(v0:number) // int
Foo123(1, 2) :- 1=1.
Bar123("abc") :- 1=1.
FooBar(x, z, y) :- Foo123(x, y), Bar123(z).
__f_oo_bar("abc") :- 1=1.
f_oo_bar2(1, "J") :- 1=1.
f_oo_bar2(42, "bla") :- 1=1.
p(1) :- 1=1.
p(7) :- 1=1.
p(255) :- 1=1.
p(-42) :- 1=1.
p(-34) :- 1=1.
p(-66) :- 1=1.
p2(x, x + 10) :- p(x).
p3(x, y) :- p2(y, x).
p1(x) :- p2(x + 1, y), p3(x, z), z > y + 10.
p4(x) :- p1(x); p2(x, _).
p5(x) :- ((p1(x), x > 10); p4(x)), !p2(x, _).
p6(x + 10 + z) :- p4(x), p4(z).
p6(t) :- p4(x), p4(t), t = x + 20.
p6(t) :- p4(x), p4(t), t = x * 30.
Bar(2) :- 1=1.
Foo(1) :- Bar(2).
Foo(x) :- Bar(x), (x = 1; x = 2; x < 10; x > 3).
BarFoo(x, z) :- FooBar(x, z, _), Foo(x).
A(x) :- BarFoo(x, _).