.decl baz(v0:number)
.decl bar(v0:__SYS_TYPE__Animal)
.decl q(v0:number)
.decl foobaz(v0:symbol)
.decl Animal_byStr(v0:symbol, v1:__SYS_TYPE__Animal)
.decl foo(v0:number)
.decl p(v0:number)
.decl Shape(v0:symbol)
.decl Animal(v0:__SYS_TYPE__Animal)
.type __SYS_TYPE_Animal_byStr = [v0:symbol]
.type __SYS_TYPE__Animal = [v0:__SYS_TYPE_Animal_byStr]
bar(v0), foo(x):- baz(x), Animal_byStr("abc", v0).
p(x):- foo(x), ((Animal_byStr("123", v0), bar(v0)); (Animal_byStr("abc", v1), bar(v1))), baz(x).
foobaz("123"):- q(42).
