.decl __f_oo_bar(v0: symbol) // string
.decl f_oo_bar2(v0: number, v1: symbol) // int x string
.output f_oo_bar2
.decl p1(v0: number) // int
.decl p2(v0: number, v1: number) // int x int
.decl p3(v0: number, v1: number) // int x int
.decl p4(v0: number) // int
.decl p5(v0: number) // int
.decl p6(v0: number) // int
.output p6
.decl p(v0: number) // int
.decl Bar(v0: number) // int
.decl Foo(v0: number) // int
__f_oo_bar("abc").
f_oo_bar2(1, "J").
f_oo_bar2(42, "bla").
p(1).
p(7).
p(255).
p(-42).
p(-34).
p(-66).
p2(x, x + 10) :- p(x).
p3(x, y) :- p2(y, x).
p1(x) :- p2(x + 1, y), p3(x, z), z > y + 10.
p4(x) :- p1(x); p2(x, _).
p5(x) :- ((p1(x), x > 10); p4(x)), !p2(x, _).
p6(x + 10 + z) :- p4(x), p4(z).
p6(t) :- p4(x), p4(t), t = x + 20.
p6(t) :- p4(x), p4(t), t = x * 30.
Bar(2).
Foo(1) :- Bar(2).
Foo(x) :- Bar(x), (x = 1; x = 2; x < 10; x > 3).
