.decl VarPointsTo(v0:symbol, v1:symbol, v2:symbol, v3:symbol) // string x string x string x string
.decl Var_Type(v0:symbol, v1:symbol) // string x string
.decl types(v0:symbol) // string
.output types
.decl foo(v0:symbol) // string
.decl bar(v0:symbol) // string
.decl foobar(v0:symbol, v1:symbol) // string x string
.output foobar
.decl GT(v0:number, v1:number) // int x int
Var_Type("Object", "o1") :- 1=1.
Var_Type("String", "str") :- 1=1.
types(?t) :- Var_Type(?t, _).
foo("abc") :- 1=1.
bar("new A") :- 1=1.
foobar(?v, ?hctx) :- foo(?v), VarPointsTo(?v, "o1", _, ?hctx), bar(?hctx).
GT(1, 0) :- 1=1.